К полю "доход_расход" нужно подтянуть "вид_дохода_расхода" из Справочника "Меппинг_опу". По значениям вид_дохода_расхода создавать доп столбцы из значений Субконто, например для процентов ППА нужен столбец с РБП

In [93]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:,.2f}'.format

In [143]:
intermediate_data_df = pd.read_parquet('intermediate_data.parquet')

In [149]:
df_91_all = intermediate_data_df.loc[intermediate_data_df['Имя_файла'].str.contains('_91.0', na=False)]
df_9101 = df_91_all.loc[df_91_all['Кт'].str.startswith('91.01')]
df_9102 = df_91_all.loc[df_91_all['Дт'].str.startswith('91.02')]

In [151]:
df_9101 = df_9101.rename(columns={'Субконто Кт_1': 'доход_расход', 'Сумма': 'оборот, тыс.ед.', 'Дт': 'Корр.счет', 'Кт': 'счет'})
CONTRACTOR_ACCOUNTS = ('58', '60', '62', '63', '66', '67', '75', '76')
mask = df_9101['Корр.счет'].astype(str).str.startswith(CONTRACTOR_ACCOUNTS, na=False)
df_9101['контрагент'] = df_9101['Субконто Дт_1'].where(mask, 'не_указано').astype('string')
df_9101['оборот, тыс.ед.'] = df_9101.loc[:, 'оборот, тыс.ед.'] / -1000
df_9101_clean = df_9101.loc[:, ['счет', 'Документ', 'Корр.счет', 'доход_расход',  'контрагент', 'оборот, тыс.ед.']]
df_9101_clean.head()

,счет,Документ,Корр.счет,доход_расход,контрагент,"оборот, тыс.ед."
112255,91.01,Корректировка долга ТЗ000000047 от 01.01.2025 ...,60.01,Доходы и расходы по результатам инвентаризации...,РТ-РЕГИСТРАТОР АО,-0.65
112256,91.01,Корректировка долга ТЗ000000062 от 01.01.2025 ...,60.02,Доходы и расходы по результатам инвентаризации СХ,ЦОК АПК ФГБУ,-0.01
112257,91.01,Оприходование товаров ТЦ000000010 от 01.01.202...,43,Доходы и расходы по результатам инвентаризации СХ,не_указано,-4.54
112258,91.01,Оприходование товаров ТЦ000000013 от 01.01.202...,43,Доходы и расходы по результатам инвентаризации СХ,не_указано,-9.23
112259,91.01,Оприходование товаров ТЗ000000003 от 01.01.202...,43,Доходы и расходы по результатам инвентаризации СХ,не_указано,-5.28

In [155]:
df_9102 = df_9102.rename(columns={'Субконто Дт_1': 'доход_расход', 'Сумма': 'оборот, тыс.ед.', 'Кт': 'Корр.счет', 'Дт': 'счет'})
mask = df_9102['Корр.счет'].astype(str).str.startswith(CONTRACTOR_ACCOUNTS, na=False)
df_9102['контрагент'] = df_9102['Субконто Кт_1'].where(mask, 'не_указано').astype('string')
df_9102['оборот, тыс.ед.'] = df_9102.loc[:, 'оборот, тыс.ед.'] / 1000
df_9102_clean = df_9102.loc[:, ['счет', 'Документ', 'Корр.счет', 'доход_расход',  'контрагент', 'оборот, тыс.ед.']]
df_9102_clean.head()

,счет,Документ,Корр.счет,доход_расход,контрагент,"оборот, тыс.ед."
122435,91.02.1,Авансовый отчет ВГ000000006 от 01.01.2025 0:00:00,71.01,Доходы (расходы) НЕ НУ,не_указано,39.71
122436,91.02.1,Операция (бухгалтерский и налоговый учет) 0000...,10.11,Доходы и расходы по результатам инвентаризации...,не_указано,-0.23
122437,91.02.1,Операция (бухгалтерский и налоговый учет) 0000...,10.11,Доходы и расходы по результатам инвентаризации...,не_указано,5.28
122438,91.02.1,Операция (бухгалтерский и налоговый учет) 0000...,10.05,Доходы и расходы по результатам инвентаризации...,не_указано,0.00
122439,91.02.1,Операция (бухгалтерский и налоговый учет) 0000...,10.05,Доходы и расходы по результатам инвентаризации...,не_указано,-0.00